language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: thegameofcodeteam@gmail.com
  api_key:
    secure: eAURDS02fBhVbmuQmExyT+VyaXJLltxnhepSvvAM1KCz9uHHUFLqhW2i823IqhnkZdVzTQWJ0DSb3t1mKhkfDu7+2hjcMQGJ1wGY24PiX8Zr7S0De80wYEcSrRv+WCSgJ/CMOvTt5fezhTZ9xc/ZN7NFz+lrWu0jXFhokOV/GuM=
  on:
    tags: true
    repo: thegameofcode/countries-info
    all_branches: true
